name: appcenter_sdk_plus
description: "AppCenter SDK written purely in Flutter with support for AppCenter Analytics and AppCenter Crashes."
version: 1.0.4
repository: https://github.com/octavian-h/appcenter_sdk_plus

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.0
  http: ^1.2.1
  logging: ^1.2.0
  package_info_plus: ^7.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqlite3_async: ^1.0.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  sqlite3_flutter_libs: ^0.5.20
